global using AutoFixture;
global using AutoFixture.AutoNSubstitute;
global using AutoFixture.Xunit2;
global using FluentAssertions;
global using NSubstitute;
global using OpenQA.Selenium;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics.CodeAnalysis;
global using Xunit;
global using static Selenium.WebDriver.Extensions.By;
global using static Selenium.WebDriver.Extensions.Tests.Shared.Trait;
global using static Softlr.Suppress;
global using SeleniumBy = OpenQA.Selenium.By;
