//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selenium.WebDriver.Extensions.IntegrationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selenium.WebDriver.Extensions.IntegrationTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;main&quot;&gt;
        ///        H1 Header
        ///    &lt;/h1&gt;
        ///    &lt;div class=&quot;main&quot; id=&quot;id1&quot;&gt;
        ///        &lt;span&gt;Query&lt;/span&gt;
        ///        &lt;span&gt;Selector&lt;/span&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;main&quot;&gt;Selenium WebDriver Extensions&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string CoreTestsHtml {
            get {
                return ResourceManager.GetString("CoreTestsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50502.
        /// </summary>
        internal static string HostUrl {
            get {
                return ResourceManager.GetString("HostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .main {
        ///            color: red;
        ///        }
        ///        div.scroll {
        ///            background: #ccc none repeat scroll 0 0;
        ///            border: 3px solid #666;
        ///            margin: 5px;
        ///            padding: 5px;
        ///            position: relative;
        ///            width: 200px;
        ///            height: 100px;
        ///            overflow: auto;
        ///        }
        ///        p {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQueryLoadedHtml {
            get {
                return ResourceManager.GetString("jQueryLoadedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .main {
        ///            color: red;
        ///        }
        ///        div.scroll {
        ///            background: #ccc none repeat scroll 0 0;
        ///            border: 3px solid #666;
        ///            margin: 5px;
        ///            padding: 5px;
        ///            position: relative;
        ///            width: 200px;
        ///            height: 100px;
        ///            overflow: auto;
        ///        }
        ///        p {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQueryUnloadedHtml {
            get {
                return ResourceManager.GetString("jQueryUnloadedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;main&quot;&gt;
        ///        H1 Header
        ///    &lt;/h1&gt;
        ///    &lt;div class=&quot;main&quot; id=&quot;id1&quot;&gt;
        ///        &lt;span&gt;Query&lt;/span&gt;
        ///        &lt;span&gt;Selector&lt;/span&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;main&quot;&gt;Selenium WebDriver Extensions&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string QuerySelectorHtml {
            get {
                return ResourceManager.GetString("QuerySelectorHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;main&quot;&gt;
        ///        H1 Header
        ///    &lt;/h1&gt;
        ///    &lt;div class=&quot;main&quot; id=&quot;id1&quot;&gt;Sizzle Selector&lt;/div&gt;
        ///    &lt;div class=&quot;main&quot;&gt;Selenium WebDriver Extensions&lt;/div&gt;
        ///    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/sizzle/2.0.0/sizzle.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SizzleLoadedHtml {
            get {
                return ResourceManager.GetString("SizzleLoadedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Selenium.WebDriver.Extensions Tests&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .main {
        ///            color: red;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;main&quot; style=&quot;width: 200px; height: 20px; padding: 10px; margin: 5px; border: 3px solid black;&quot;&gt;
        ///        H1 Header
        ///    &lt;/h1&gt;
        ///    &lt;div class=&quot;main&quot; id=&quot;id1&quot; style=&quot;background-color: green; z-index: 1;&quot;&gt;
        ///        &lt;span&gt;Sizzle&lt;/span&gt;
        ///        &lt;span&gt;Selenium&lt;/span&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SizzleUnloadedHtml {
            get {
                return ResourceManager.GetString("SizzleUnloadedHtml", resourceCulture);
            }
        }
    }
}
