name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test test/Selenium.WebDriver.Extensions.Tests -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

  sonarcloud:
    runs-on: windows-latest
    
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Cache SonarCloud Packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarCloud Scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarCloud Scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Build and Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:selenium.webdriver.extensions /o:softlr /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
        dotnet build -c Release
        dotnet test test/Selenium.WebDriver.Extensions.Tests -c Release --logger trx -o ./TestResults/ -p:CollectCoverage=true -p:CoverletOutputFormat="json%2copencover" -p:CoverletOutput=./TestResults/ -p:MergeWith=./TestResults/coverage.json
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

  integration-tests:
    name: integration-tests-${{ matrix.os }}-${{ matrix.browser }}
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [ Chrome, Firefox ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test test/Selenium.WebDriver.Extensions.IntegrationTests -c Release --filter Browser=${{ matrix.browser }}
  
  integration-tests2:
    name: integration-tests-${{ matrix.browser }}
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [ Edge, InternetExplorer ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test test/Selenium.WebDriver.Extensions.IntegrationTests -c Release --filter Browser=${{ matrix.browser }}
