name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test test/Selenium.WebDriver.Extensions.Tests -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
