name: Release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Verify Commit
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    
    - name: Set VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build
      run: dotnet build -c Release -p:Version=${VERSION}
    
    - name: Test
      run: dotnet test test/Selenium.WebDriver.Extensions.Tests -c Release -p:Version=${VERSION}
    
    - name: Pack
      run: dotnet pack -c Release -p:Version=${VERSION} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --no-build -o .
    
    - name: Push
      run: dotnet nuget push Selenium.WebDriver.Extensions.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
